#include "IO.h"


void gpio_init( GPIO_Module* GPIO_Port, uint32_t Mode, uint32_t Gpio_Rate, uint16_t Pin)
{
    GPIO_InitType GPIO_InitStructure;

    GPIO_Structure_Initialize(&GPIO_InitStructure);
	
	
	
    GPIO_InitStructure.Pin       = Pin;
    GPIO_InitStructure.GPIO_Mode = Mode;
    GPIO_InitStructure.GPIO_Current   = GPIO_DS_4MA;
	  GPIO_InitStructure.GPIO_Slew_Rate = Gpio_Rate;
	
    GPIO_Peripheral_Initialize(GPIO_Port, &GPIO_InitStructure);

}

void IO_Init(void)
{
    //////// Output ////////
		INHALE_GPIO_OFF();
	  gpio_init(INHALE_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,INHALE_GPIO_PIN);
	
		RUBBISH_FULL_LED_OFF();
	  gpio_init(RUBBISH_FULL_LED_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,RUBBISH_FULL_LED_GPIO_PIN);
	  
		CLEAN_LED_OFF();
	  gpio_init(CLEAN_LED_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,CLEAN_LED_GPIO_PIN);

		FAULT_LED_OFF();
	  gpio_init(FAULT_LED_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,FAULT_LED_GPIO_PIN);
	
		CLEAN_LED_OFF();
	  gpio_init(CLEAN_LED_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,CLEAN_LED_GPIO_PIN);

		RUBBISH_IR_TX_OFF();
	  gpio_init(RUBBISH_IR_TX_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,RUBBISH_IR_TX_GPIO_PIN);
	
		MAGNETIC_VALVE_CTRL_OFF();
	  gpio_init(MAGNETIC_VALVE_CTRL_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,MAGNETIC_VALVE_CTRL_GPIO_PIN);
	
		MAGNETIC_VALVE_CTRL_OFF();
	  gpio_init(BRUSH_FAN_CTRL_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,BRUSH_FAN_CTRL_GPIO_PIN);
	
		MAGNETIC_VALVE_CTRL_OFF();
	  gpio_init(RUBBISH_FAN_CTRL_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,RUBBISH_FAN_CTRL_GPIO_PIN);
		
		DRAIN_VALVE_CTRL_OFF();
	  gpio_init(DRAIN_VALVE_CTRL_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,DRAIN_VALVE_CTRL_GPIO_PIN);

		DRAIN_VALVE_PWM_OFF();
	  gpio_init(DRAIN_VALVE_PWM_GPIO_PORT,GPIO_MODE_OUT_PP,GPIO_SLEW_RATE_FAST,DRAIN_VALVE_PWM_GPIO_PIN);

    //////// Input ////////
		
		gpio_init(VALVE_LIQUID_LEVEL_GPIO_PORT, GPIO_MODE_INPUT, GPIO_SLEW_RATE_FAST, VALVE_LIQUID_LEVEL_GPIO_PIN);
		
		gpio_init(CLEANING_SOLUTION_CHECK_PORT, GPIO_MODE_INPUT, GPIO_SLEW_RATE_FAST, CLEANING_SOLUTION_CHECK_PIN);
		
		gpio_init(TRASH_BASKET_CHECK_PORT, GPIO_MODE_INPUT, GPIO_SLEW_RATE_FAST, TRASH_BASKET_CHECK_PIN);
		
		gpio_init(DRAIN_VALVE_LEFT_SENSE_PORT, GPIO_MODE_INPUT, GPIO_SLEW_RATE_FAST, DRAIN_VALVE_LEFT_SENSE_PIN);
		
		gpio_init(DRAIN_VALVE_RIGHT_SENSE_PORT, GPIO_MODE_INPUT, GPIO_SLEW_RATE_FAST, DRAIN_VALVE_RIGHT_SENSE_PIN);

		gpio_init(TANK_CLEAR_FULL_CHECK_PORT, GPIO_MODE_INPUT, GPIO_SLEW_RATE_FAST, TANK_CLEAR_FULL_CHECK_PIN);

		gpio_init(TANK_CLEAR_NOT_WATER_CHECK_PORT, GPIO_MODE_INPUT, GPIO_SLEW_RATE_FAST, TANK_CLEAR_NOT_WATER_CHECK_PIN);
		
		//open rubbish tx

		RUBBISH_IR_TX_ON();
		RUBBISH_IR_TX2_ON();
		
		LOG_DEB("Bsp GPIO init finish.");

}

