#ifndef _IO_H
#define _IO_H

#include "includes.h"


/*Output*/
#define INHALE_GPIO_PORT      				GPIOA
#define INHALE_GPIO_PIN       				GPIO_PIN_9
#define INHALE_GPIO_OFF()          	 {GPIO_Pins_Reset(INHALE_GPIO_PORT,INHALE_GPIO_PIN);} 
#define INHALE_GPIO_ON()           	 {GPIO_Pins_Set(INHALE_GPIO_PORT,INHALE_GPIO_PIN);} 

//LED CTRL
#define RUBBISH_FULL_LED_GPIO_PORT      GPIOB
#define RUBBISH_FULL_LED_GPIO_PIN       GPIO_PIN_3
#define RUBBISH_FULL_LED_OFF()          {GPIO_Pins_Reset(RUBBISH_FULL_LED_GPIO_PORT,RUBBISH_FULL_LED_GPIO_PIN);} 
#define RUBBISH_FULL_LED_ON()           {GPIO_Pins_Set(RUBBISH_FULL_LED_GPIO_PORT,RUBBISH_FULL_LED_GPIO_PIN);} 

#define CLEAN_LED_GPIO_PORT      				GPIOA
#define CLEAN_LED_GPIO_PIN       				GPIO_PIN_15
#define CLEAN_LED_OFF()          				{GPIO_Pins_Reset(CLEAN_LED_GPIO_PORT,CLEAN_LED_GPIO_PIN);}
#define CLEAN_LED_ON()           				{GPIO_Pins_Set(CLEAN_LED_GPIO_PORT,CLEAN_LED_GPIO_PIN);}

#define FAULT_LED_GPIO_PORT      				GPIOD
#define FAULT_LED_GPIO_PIN       				GPIO_PIN_13
#define FAULT_LED_OFF()          				{GPIO_Pins_Reset(FAULT_LED_GPIO_PORT,FAULT_LED_GPIO_PIN);} 
#define FAULT_LED_ON()           				{GPIO_Pins_Set(FAULT_LED_GPIO_PORT,FAULT_LED_GPIO_PIN);} 

//RUBBISH IR TX RX
#define RUBBISH_IR_TX_GPIO_PORT         GPIOB
#define RUBBISH_IR_TX_GPIO_PIN          GPIO_PIN_2
#define RUBBISH_IR_TX_OFF()             {GPIO_Pins_Reset(RUBBISH_IR_TX_GPIO_PORT,RUBBISH_IR_TX_GPIO_PIN);} 
#define RUBBISH_IR_TX_ON()              {GPIO_Pins_Set(RUBBISH_FULL_LED_GPIO_PORT,RUBBISH_IR_TX_GPIO_PIN);} 

#define RUBBISH_IR_RX_GPIO_PORT         GPIOB
#define RUBBISH_IR_RX_GPIO_PIN          GPIO_PIN_10
#define RUBBISH_IR_RX_READ()            GPIO_Input_Pin_Data_Get(RUBBISH_IR_RX_GPIO_PORT,RUBBISH_IR_RX_GPIO_PIN) 

//Drain Valve Liquid Level CHECK
#define VALVE_LIQUID_LEVEL_GPIO_PORT    GPIOB
#define VALVE_LIQUID_LEVEL_GPIO_PIN     GPIO_PIN_11
#define VALVE_LIQUID_LEVEL_READ()       GPIO_Input_Pin_Data_Get(VALVE_LIQUID_LEVEL_GPIO_PORT,VALVE_LIQUID_LEVEL_GPIO_PIN)

//Magnetic Valve Ctrl 
#define MAGNETIC_VALVE_CTRL_GPIO_PORT   GPIOB
#define MAGNETIC_VALVE_CTRL_GPIO_PIN    GPIO_PIN_1
#define MAGNETIC_VALVE_CTRL_OFF()       {GPIO_Pins_Reset(MAGNETIC_VALVE_CTRL_GPIO_PORT,MAGNETIC_VALVE_CTRL_GPIO_PIN);} 
#define MAGNETIC_VALVE_CTRL_ON()        {GPIO_Pins_Set(MAGNETIC_VALVE_CTRL_GPIO_PORT,MAGNETIC_VALVE_CTRL_GPIO_PIN);} 

//BRUSH FAN CTRL
#define BRUSH_FAN_CTRL_GPIO_PORT         GPIOA
#define BRUSH_FAN_CTRL_GPIO_PIN          GPIO_PIN_4
#define BRUSH_FAN_CTRL_OFF()             {GPIO_Pins_Reset(BRUSH_FAN_CTRL_GPIO_PORT,BRUSH_FAN_CTRL_GPIO_PIN);} 
#define BRUSH_FAN_CTRL_ON()              {GPIO_Pins_Set(BRUSH_FAN_CTRL_GPIO_PORT,BRUSH_FAN_CTRL_GPIO_PIN);} 

//RUBBISH FAN CTRL
#define RUBBISH_FAN_CTRL_GPIO_PORT       GPIOA
#define RUBBISH_FAN_CTRL_GPIO_PIN        GPIO_PIN_6
#define RUBBISH_FAN_CTRL_OFF()           {GPIO_Pins_Reset(RUBBISH_FAN_CTRL_GPIO_PORT,RUBBISH_FAN_CTRL_GPIO_PIN);} 
#define RUBBISH_FAN_CTRL_ON()            {GPIO_Pins_Set(RUBBISH_FAN_CTRL_GPIO_PORT,RUBBISH_FAN_CTRL_GPIO_PIN);} 

//Cleaning Solution state Check
#define CLEANING_SOLUTION_CHECK_PORT     GPIOA
#define CLEANING_SOLUTION_CHECK_PIN      GPIO_PIN_2
#define CLEANING_SOLUTION_CHECK_READ()   GPIO_Input_Pin_Data_Get(CLEANING_SOLUTION_CHECK_PORT,CLEANING_SOLUTION_CHECK_PIN)

//Trash Basket in place check
#define TRASH_BASKET_CHECK_PORT          GPIOC
#define TRASH_BASKET_CHECK_PIN           GPIO_PIN_13
#define TRASH_BASKET_CHECK_READ()        GPIO_Input_Pin_Data_Get(TRASH_BASKET_CHECK_PORT,TRASH_BASKET_CHECK_PIN)

void gpio_init( GPIO_Module *GPIO_Port, uint32_t Mode, uint32_t Gpio_Rate, uint16_t Pin);

void IO_Init(void);



#endif
